import AdminLayout from 'components/Layouts/AdminLayout';
import { NextPage } from 'next';
import React from 'react';

const AdminBooksPage: NextPage = () => {
    return (
        <AdminLayout>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
            <div>a</div>
            <div>b</div>
        </AdminLayout>
    );
};

export default AdminBooksPage;
